import './globals.css'
import NavBar from '@/components/nav'
import Footer from '@/components/footer'

export const metadata = {
  title: 'Timothy Sung\'s Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
